import React from "react";
import Viresonapp from "../Viresonapp";

function TermsofService() {
  return (
    <>
      <div className="object-cover mx-4 md:mx-48 my-8 md:my-16 h-36 md:h-72 bg-[rgb(0,69,120)] rounded-3xl">
        <div className="px-12 py-12 text-4xl font-medium self-center md:text-7xl text-cyan-50 md:py-24 md:px-72">
          Terms of Service
        </div>
      </div>
      <div className="px-4 md:px-20 py-20">
        <div className="font-bold">Effective Date: July 01, 2024</div>
        <div className="p-5 font-medium">1. Introduction</div>
        <div className="p-2">
          Welcome to Agape Acts, an app provided by LBIC Consulting Services,
          Inc. doing business as Agape Acts (“we,” “us,” “our”). These Terms and
          Conditions, often referred to as a “Terms of Service” or “User
          Agreement,” constitute a legal contract between the app provider and
          the users of Agape Acts. By using our app, you agree to comply with
          and be bound by these Terms and Conditions. Please read these Terms
          and Conditions carefully before using Agape Acts.
        </div>
        <div className="p-5 font-medium">2. Acceptance of Terms</div>
        <div className="p-2">
          2.1. By using Agape Acts, you agree to abide by these Terms and
          Conditions. Your acceptance of these terms is confirmed by an “I
          Accept” button during the app registration or installation process.
        </div>
        <div className="p-5 font-medium">3. User Eligibility</div>
        <div className="p-2">
          3.1. You must be of the age required by applicable laws in your
          jurisdiction to use Agape Acts. If you are under the required age, you
          may not use the app.
        </div>
        <div className="p-5 font-medium">4. User Accounts</div>
        <div className="p-2">
          4.1. Users are responsible for creating and maintaining their
          accounts. You are responsible for safeguarding your login credentials.
          Sharing accounts or login information is strictly prohibited.
        </div>
        <div className="p-5 font-medium">5. Privacy Policy</div>
        <div className="p-2">
          5.1. Your use of Agape Acts is also governed by our Privacy Policy,
          which outlines how user data is collected, used, and protected. You
          can find our Privacy Policy [here] (insert link to privacy policy).
        </div>
        <div className="p-5 font-medium">6. User Conduct</div>
        <div className="p-2">
          6.1. Users must engage in acceptable behavior while using Agape Acts.
          Harassment, hate speech, spam, or any other prohibited activities are
          strictly forbidden.
        </div>
        <div className="p-5 font-medium">7. Intellectual Property</div>
        <div className="p-2">
          7.1. All intellectual property, including copyrights, trademarks, and
          other proprietary rights related to Agape Acts, are owned by LBIC
          Consulting Services, Inc. Users are restricted from using, copying, or
          distributing any content generated by the app without explicit
          permission.
        </div>
        <div className="p-5 font-medium">8. Content Guidelines</div>
        <div className="p-2">
          8.1. If applicable, users must adhere to guidelines for user-generated
          content, including restrictions on posting, sharing, or uploading
          content. Violation of these guidelines may result in account
          suspension or termination.
        </div>
      </div>
      <Viresonapp />
    </>
  );
}

export default TermsofService;
